EShop.Web/Areas/Admin/Controllers/ContactUsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EShop.Common.DTOs;
using EShop.Common.DTOs.ContactUs;
using EShop.Common.Services.EmailTools;
using EShop.Data.Models;
using EShop.Data.Repositories.GenericRepository;
using EShop.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace EShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactUsController : Controller
    {
        private IGenericRepository<ContactUs> _repository;

        public ContactUsController(IGenericRepository<ContactUs> repository)
        {
            _repository = repository;
        }

        [Route("/Admin/ContactUs/{pageId:long:positive?}")]
        public async Task<IActionResult> Index(CancellationToken cancellationToken, long? pageId = 1)
        {
            var model = await _repository.GetAllAsync(cancellationToken);
            return View("Index", new ViewModelWithPageInfo<IEnumerable<ContactUs>>()
            {
                ViewModel = model.Skip((int)(pageId - 1) * 10).Take(10).OrderByDescending(o=>o.ContactUsId),
                PaginationInfo = new PaginationInfo()
                {
                    CurrentPage = (int)pageId,
                    ItemPerPage = 10,
                    TotalItems = model.Count()
                }
            });
        }

        [HasIdParameter]
        public async Task<IActionResult> Detail([FromRoute]long id, CancellationToken cancellationToken)
        {
            var contactUs = await _repository.FindAsync(id, cancellationToken);
            if (contactUs is null)
            {
                return NotFound();
            }

            return View("Detail", contactUs);
        }

        [HttpGet]
        [HasIdParameter]
        public async Task<IActionResult> MessageResponse([FromRoute]long id, CancellationToken cancellationToken)
        {
            var contactUs = await _repository.FindAsync(id, cancellationToken);
            if (contactUs is null || contactUs.HasResponse)
            {
                return NotFound();
            }

            ViewData["Message"] = contactUs.Message;
            return View("MessageResponse", new ContactUsResponseViewModel()
            {
                MessageId = contactUs.ContactUsId,
                Email = contactUs.Email
            });
        }

        [HttpPost]
        [HasIdParameter]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MessageResponse([FromRoute] long id,[FromForm]ContactUsResponseViewModel model, CancellationToken cancellationToken)
        {
            var contactUs = await _repository.FindAsync(id, cancellationToken);
            if (model.MessageId.Equals(id) && model.Email.Equals(contactUs.Email))
            {
                if (ModelState.IsValid)
                {
                    if (await EmailSender.SendAsync(model.Email, model.Response, "پاسخ به تماس شما در سایت"))
                    {
                        contactUs.HasResponse = true;
                        await _repository.UpdateAsync(contactUs, cancellationToken);
                        return RedirectToAction(nameof(Index));
                    }
                    ModelState.AddModelError("All", "ایمیل ارسال نشد دوباره تلاش کنید");
                    return View("MessageResponse", model);
                }
                ModelState.AddModelError("All", "پاسخ نمیتواند خالی باشد");
                return View("MessageResponse", model);
            }

            return BadRequest();
        }
    }
}

EShop.Web/Pages/ContactUs/Index.cshtml.cs
using System.Threading;
using System.Threading.Tasks;
using EShop.Common.Services.GoogleRecaptcha;
using EShop.Data.Repositories.GenericRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Model = EShop.Data.Models;

namespace EShop.Web.Pages.ContactUs
{
    public class IndexModel : PageModel
    {
        private IConfiguration _configuration;
        private IGenericRepository<Model.ContactUs> _repository;

        public IndexModel(IConfiguration configuration, IGenericRepository<Model.ContactUs> repository)
        {
            _configuration = configuration;
            _repository = repository;
        }

        public Model::ContactUs ContactUs { get; set; }
        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromForm][Bind("Email,PhoneNumber,Message")]Model.ContactUs contactUs, CancellationToken cancellationToken)
        {
            if (await RecaptchaValidator.IsValid(_configuration["SecretKey"], Request.Form["g-recaptcha-response"]))
            {
                if (ModelState.IsValid)
                {
                    await _repository.AddAndSaveAsync(contactUs, cancellationToken);
                    return Redirect("/ContactUs?success=true");
                }

                return Page();
            }
            ModelState.AddModelError("All", "لطفا من ربات نیستم را تایید کنید");
            return Page();
        }
    }
}

EShop.Web/Areas/Admin/Views/ContactUs/Detail.cshtml
@model ContactUs
@{
    ViewBag.Title = "اطلاعات تماس";
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">

                <div class="card-title-wrap bar-primary">
                    <h4 class="card-title">
                        اطلاعات پیام
                    </h4>
                </div>

                <a class="heading-elements-toggle">
                    <i class="la la-ellipsis-v font-medium-3"></i>
                </a>

            </div>
            <div class="card-content mt-1 mr-2">
                <p class="text-dark">ایمیل : @Model.Email</p>
                <p class="text-dark">شماره تلفن : @Model.PhoneNumber</p>
                <p class="text-dark">متن پیام :</p>
                <div class="container-fluid">
                    <div class="border border-blue p-2">
                        @Model.Message
                    </div>
                </div>
                <p class="">وضعیت : @(Model.HasResponse ? "پاسخ داده شده" : "بدون پاسخ" )</p>
                @if (!Model.HasResponse)
                {
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <a class="btn btn-block btn-success" asp-area="Admin" asp-controller="ContactUs" asp-action="MessageResponse" asp-route-id="@Model.ContactUsId">ارسال پاسخ</a>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <a class="btn btn-block btn-link" asp-area="Admin" asp-controller="ContactUs" asp-action="Index">بازگشت</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

EShop.Web/Areas/Admin/Views/ContactUs/Index.cshtml
@model ViewModelWithPageInfo<IEnumerable<ContactUs>>
@{
    ViewBag.Title = "لیست تماس با ما";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">

                <div class="card-title-wrap bar-primary">
                    <h4 class="card-title">
                        لیست پیغام ها
                    </h4>
                </div>

                <a class="heading-elements-toggle">
                    <i class="la la-ellipsis-v font-medium-3"></i>
                </a>

            </div>
            <div class="card-content mt-1">
                <div class="table-responsive">
                    <table class="table table-hover table-xl mb-0" id="recent-orders">
                        <thead>
                            <tr>
                                <th class="border-top-0">کد پیام</th>
                                <th class="border-top-0">ایمیل</th>
                                <th class="border-top-0">متن</th>
                                <th class="border-top-0">وضعیت</th>
                                <th class="border-top-0">دستورات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.ViewModel.Any())
                            {
                                @foreach (var item in Model.ViewModel)
                                {
                                    <tr>
                                        <td class="text-truncate">
                                          @item.ContactUsId
                                        </td>
                                        <td class="text-truncate">
                                            <a class="btn btn-link" href="mailto:@item.Email">@item.Email</a>
                                        </td>
                                        <td class="text-truncate">
                                            @item.Message.Substring(0, 50) ...
                                        </td>
                                        <td class="text-truncate">
                                            @if (item.HasResponse)
                                            {
                                                <p class="text-success">پاسخ داده شده</p>
                                            }
                                            else
                                            {
                                                <p class="text-danger">بدون پاسخ</p>
                                            }
                                        </td>
                                        <td>
                                            <a class="btn btn-sm btn-outline-danger round mb-0" asp-area="Admin" asp-controller="ContactUs" asp-action="Detail" asp-route-id="@item.ContactUsId">مشاهده</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <th colspan="4" class="text-truncate text-danger">در حال حاضر تماسی است</th>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @if (Model.ViewModel.Any())
                    {
                        <div class="mt-1">

                            <div class="dataTables_paginate paging_simple_numbers" page-info="@Model.PaginationInfo" action="Index" controller="ContactUs"></div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

EShop.Web/Areas/Admin/Views/ContactUs/MessageResponse.cshtml
@model ContactUsResponseViewModel
@{
    ViewBag.Title = "ارسال پاسخ";
}
@section css
{
    <link href="/Admin-Assets/vendors/css/sweetalert2.min.css" rel="stylesheet" />
}
<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="card-title-wrap bar-success">
						<h4 class="card-title mb-0">پاسخ به @Model.Email</h4>
					</div>
				</div>
				<div class="card-body">
					<div class="px-3">
                        <form class="form" asp-area="Admin" asp-controller="ContactUs" asp-action="MessageResponse" method="post" id="form">
                            <input type="hidden" asp-for="MessageId"/>
                            <input type="hidden" asp-for="Email"/>
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-12 mb-1">
                                        <fieldset class="form-group">
                                            <div class="m-1 p-2 border border-danger">
                                                در حال پاسخ به : @ViewData["Message"]
                                            </div>
                                            <label>پاسخ</label>
                                            <textarea asp-for="Response" class="form-control round" placeholder="پاسخ پیام را وارد کنید"></textarea>
                                        </fieldset>
                                    </div>
                                </div>
                                @Html.AntiForgeryToken()
                            </div>
                            <div class="text-danger" asp-validation-summary="All"></div>
                        </form>
                        <a class="btn btn-success" onclick="GenericFormSubmitWarning('form', 'آیا از یاسخ مطمعن هستید ؟')">
                            <i class="icon-paper-plane"></i>
                        </a>
					</div>
				</div>
			</div>
		</div>
	</div>

@section script
{
<script src="/Admin-Assets/vendors/js/sweetalert2.min.js"></script>
<script asp-src-include="/lib/**.js"></script>
<script src="//cdn.ckeditor.com/4.19.0/full/ckeditor.js"></script>
<script>
    CKEDITOR.replace("Response");
</script>
}