EShop.Web/Areas/Admin/Controllers/BrandController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EShop.Common.DTOs;
using EShop.Common.Services.Image;
using EShop.Data.Models;
using EShop.Data.Repositories.GenericRepository;
using EShop.Web.Filters;
using EShop.Web.Tools;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EShop.Web.Areas.Admin.Controllers
{
    [AutoValidateAntiforgeryToken]
    [Area("Admin")]
    public class BrandController : Controller
    {
        private IGenericRepository<Brand> _repository;

        public BrandController(IGenericRepository<Brand> repository)
        {
            _repository = repository;
        }

        [Route("/Admin/Brand/{pageId:positive?}")]
        public async Task<IActionResult> Index([FromRoute] int pageId = 1, CancellationToken cancellationToken = default)
        {
            var model = await _repository.GetAllAsync(cancellationToken);

            return View("Index", new ViewModelWithPageInfo<IEnumerable<Brand>>()
            {
                PaginationInfo = new PaginationInfo()
                {
                    ItemPerPage = 3,
                    TotalItems = model.Count(),
                    CurrentPage = pageId
                },
                ViewModel = model.Skip((pageId - 1) * 3).Take(3)
            });
        }

        #region Create New Brand

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm][Bind("Name,Description,Image")] Brand brand,
            [FromForm] IFormFile brandImage, CancellationToken cancellationToken = default)
        {
            if (!ImageCheck(brandImage))
            {
                return View("Create", brand);
            }

            if (ModelState.IsValid)
            {
                brand.Image = ImageNameGenerator.Generate();
                await brandImage.SaveAsync("BrandImage", brand, cancellationToken);
                await _repository.AddAndSaveAsync(brand, cancellationToken);
                return RedirectToAction(nameof(Index));
            }

            return View("Create", brand);
        }

        #endregion

        #region Brand Detail


        [HasIdParameter]
        public async Task<IActionResult> Detail([FromRoute] long id, CancellationToken cancellationToken = default)
        {
            Brand brand = await _repository.FindAsync(id, cancellationToken);
            if (brand != null)
            {
                return View("Detail", brand);
            }

            return NotFound();
        }
        #endregion

        #region Edit Brand

        [HttpGet]
        [HasIdParameter]
        public async Task<IActionResult> Edit([FromRoute] long id, CancellationToken cancellationToken = default)
        {
            Brand brand = await _repository.FindAsync(id, cancellationToken);
            if (brand != null)
            {
                return View("Edit", brand);
            }

            return NotFound();

        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm][Bind("BrandId,Name,Description,Image")] Brand brand,
            [FromForm] IFormFile brandImage, CancellationToken cancellationToken)
        {
            if (brandImage != null && ImageCheck(brandImage))
            {
                await brandImage.SaveAsync("BrandImage", brand, cancellationToken);
            }

            if (ModelState.IsValid)
            {
                await _repository.UpdateAsync(brand, cancellationToken);
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError("All", "لطفا همه فیلد ها را پر کنید");
            return View("Edit", brand);
        }

        #endregion


        [NonAction]
        private bool ImageCheck(IFormFile image)
        {
            ModelState.Remove("Image");
            if (ImageValidator.IsImageNull(image))
            {
                ModelState.AddModelError("All", "تصویر برند نمیتواند خالی باشد");
                return false;
            }
            else if (!ImageValidator.IsImageExtensionPng(image))
            {
                ModelState.AddModelError("All", "پسوند فایل معتبر نیست . فقط فرمت (*.png) مورد قبول است");
                return false;
            }
            else if (!ImageValidator.IsImageSizeValid(image))
            {
                ModelState.AddModelError("All", "حجم تصویر بیشتر از حد مجاز است. حجم مورد قبول (1MB) میباشد");
                return false;
            }

            return true;
        }
    }
}

EShop.Web/Controllers/BrandController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EShop.Common.DTOs;
using EShop.Data.Models;
using EShop.Data.Repositories.GenericRepository;
using EShop.Web.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace EShop.Web.Controllers
{
    [ViewComponent(Name = "BrandHybridViewComponent")]
    public class BrandController : Controller
    {
        private IGenericRepository<Brand> _repository;

        public BrandController(IGenericRepository<Brand> repository)
        {
            _repository = repository;
        }

        [Route("/Brand/{pageId:positive?}")]
        public async Task<IActionResult> Index([FromRoute]int pageId = 1)
        {
            var model = await _repository.GetAllAsync();
            return View("Index", new ViewModelWithPageInfo<IEnumerable<Brand>>()
            {
                PaginationInfo = new PaginationInfo()
                {
                    TotalItems = model.Count(),
                    ItemPerPage = 3,
                    CurrentPage = pageId
                },
                ViewModel = model.Skip((pageId - 1) * 3).Take(3)
            });
        }

        [Route("/Brand/Detail/{id:long}")]
        [HasIdParameter]
        public async Task<IActionResult> Detail([FromRoute] long id)
        {
            Brand brand = await _repository.FindAsync(id);
            if (brand is null)
            {
                return NotFound();
            }
            return View("Detail", brand);
        }

        [ViewComponentContext]
        public ViewComponentContext ComponentContext { get; set; }

        public async Task<ViewViewComponentResult> InvokeAsync()
        {
            var model = await _repository.GetAllAsync();
            return new ViewViewComponentResult()
            {
                ViewData = new ViewDataDictionary<IQueryable<Brand>>(ComponentContext.ViewData, model.OrderByDescending(o=>o.BrandId).Take(3))
            };
        }
    }
}

EShop.Web/Areas/Admin/Views/Brand/Create.cshtml
@{
    ViewBag.Title = "افزودن برند جدید";
}

@model Brand

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title-wrap bar-success">
                    <h4 class="card-title mb-0">ثبت اطلاعات برند</h4>
                </div>
            </div>
            <div class="card-body">
                <div class="px-3">
                    <form class="form" asp-area="Admin" asp-controller="Brand" asp-action="Create" method="post" enctype="multipart/form-data">
                        <div class="form-body">
                            <div class="col-xl-6 col-lg-6 col-md-12 mb-1">
                                <fieldset class="form-group">
                                    <label asp-for="Name"></label>
                                    <input asp-for="Name" class="form-control round" placeholder="نام برند">
                                </fieldset>
                            </div>

                            <div class="col-xl-12 col-lg-12 col-md-12 mb-1">
                                <fieldset class="form-group">
                                    <label asp-for="Description"></label>
                                    <textarea class="form-control" asp-for="Description" placeholder="توضیحات کوتاه درباره برند" rows="6"></textarea>
                                </fieldset>
                            </div>

                            <div class="col-xl-6 col-lg-6 col-md-12 mb-1">
                                <div class="card">
                                    <div class="card card-header">
                                        تصویر بارگذاری شده
                                    </div>
                                    <div class="card card-body">
                                        <img class="img-thumbnail col-6" height="200" src="/Images/BrandImage/samsung.png" id="perview_image" />
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">بازگذاری تصویر</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="imgInp" name="brandImage">
                                        <label class="custom-file-label" for="inputGroupFile01">انتخاب فایل</label>
                                    </div>
                                </div>
                                @Html.AntiForgeryToken()
                                <div class="col-xl-12 col-lg-12 col-md-12 mb-1">
                                    <fieldset class="form-group">
                                        <div class="text-danger" asp-validation-summary="All">
                                        </div>
                                        <button type="submit" class="btn btn-primary">ثبت برند</button>
                                    </fieldset>
                                </div>

                            </div>
                        </div>
                    </form>
                    <div class="col-lg-3 col-md-12 col-sm-12 p-1">
                        <a class="btn btn-danger" asp-area="Admin" asp-controller="Brand" asp-action="Index">
                            <i class="icon-arrow-left"></i> بازگشت
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section script
{
    <script asp-src-include="/lib/**.js"></script>
    <script src="//cdn.ckeditor.com/4.19.0/full/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Description");
    </script>
}

EShop.Web/Areas/Admin/Views/Brand/Detail.cshtml
@{
    ViewBag.Title = $"اطلاعات برند {Model.Name}";
}

@model Brand


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title-wrap bar-success">
                    <h4 class="card-title mb-0">@Model.Name (@Model.BrandId)</h4>
                </div>
            </div>
            <div class="card-body">
                <div class="px-3">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                            <img src="/Images/BrandImage/@Model.Image" title="تصویر برند @Model.Name" alt="@Model.Name" height="300" class="img-thumbnail"/>
                        </div>
                        
                        <div class="col-12 mt-2">
                            <h5>توضیحات برند : </h5>
                            @Html.Raw(Model.Description)
                        </div>
                    </div>
                </div>
                <a class="btn btn-danger mr-3 mt-3" asp-area="Admin" asp-action="Index" asp-controller="Brand">بازگشت <i class="icon-arrow-left"></i></a>
            </div>
        </div>
    </div>
</div>

EShop.Web/Areas/Admin/Views/Brand/Edit.cshtml
@{
    ViewBag.Title = $"ویرایش برند {Model.Name}";
}
@model Brand

@section css
{
<link rel="stylesheet" href="/Admin-Assets/vendors/css/sweetalert2.min.css">
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title-wrap bar-success">
                    <h4 class="card-title mb-0">ویرایش اطلاعات برند @Model.Name</h4>
                </div>
            </div>
            <div class="card-body">
                <div class="px-3">
                    <form class="form" asp-area="Admin" asp-action="Edit" asp-controller="Brand" id="Edit-Brand-Form" method="post" enctype="multipart/form-data">
                        <div class="form-body">
                            <input type="hidden" asp-for="BrandId"/>
                            <input type="hidden" asp-for="Image"/>
                            <div class="col-xl-6 col-lg-6 col-md-12 mb-1">
                                <fieldset class="form-group">
                                    <label asp-for="Name"></label>
                                    <input asp-for="Name" class="form-control round" placeholder="نام برند">
                                </fieldset>
                            </div>

                            <div class="col-xl-12 col-lg-12 col-md-12 mb-1">
                                <fieldset class="form-group">
                                    <label asp-for="Description"></label>
                                    <textarea class="form-control" asp-for="Description" placeholder="توضیحات کوتاه درباره برند" rows="6"></textarea>
                                </fieldset>
                            </div>

                            <div class="col-xl-6 col-lg-6 col-md-12 mb-1">
                                <div class="card">
                                    <div class="card card-header">
                                        تصویر بارگذاری شده
                                    </div>
                                    <div class="card card-body">
                                        <img class="img-thumbnail col-6" title="@Model.Name" height="200" src="/Images/BrandImage/@Model.Image" alt="برند @Model.Name" id="perview_image"/>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">بازگذاری تصویر</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="imgInp" name="brandImage">
                                        <label class="custom-file-label" for="inputGroupFile01">انتخاب فایل</label>
                                    </div>
                                </div>
                                @Html.AntiForgeryToken()
                                <div class="col-xl-12 col-lg-12 col-md-12 mb-1">
                                    <fieldset class="form-group">
                                        <div class="text-danger" asp-validation-summary="All">
                                        </div>
                                    </fieldset>
                                </div>
                                <a class="btn btn-primary" onclick="GenericFormSubmitWarning('Edit-Brand-Form', 'آیا از ویرایش این برند اطمینان دارید ؟')">ویرایش برند</a>
                            </div>
                        </div>
                    </form>
                    <div class="col-lg-3 col-md-12 col-sm-12 p-1">
                        <a class="btn btn-danger" asp-area="Admin" asp-action="Index" asp-controller="Brand">
                            <i class="icon-arrow-left"></i> بازگشت
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section script
{
<script src="/Admin-Assets/vendors/js/sweetalert2.min.js"></script>
<script asp-src-include="/lib/**.js"></script>
<script src="//cdn.ckeditor.com/4.19.0/full/ckeditor.js"></script>
<script>
    CKEDITOR.replace("Description");
</script>
}

EShop.Web/Areas/Admin/Views/Brand/Index.cshtml
@{
    ViewBag.Title = "لیست برند ها";
}

@model ViewModelWithPageInfo<IEnumerable<Brand>>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">

                <div class="card-title-wrap bar-primary">
                    <h4 class="card-title">
                        لیست برند ها
                    </h4>
                </div>

                <a class="heading-elements-toggle">
                    <i class="la la-ellipsis-v font-medium-3"></i>
                </a>

                <a class="btn btn-success" asp-area="Admin" asp-action="Create" asp-controller="Brand">افزودن برند جدید</a>

            </div>
            <div class="card-content mt-1">
                <div class="table-responsive">
                    <table class="table table-hover table-xl mb-0" id="recent-orders">
                        <thead>
                            <tr>
                                <th class="border-top-0">کد برند</th>
                                <th class="border-top-0">نام</th>
                                <th class="border-top-0">تصویر</th>
                                <th class="border-top-0">دستورات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.ViewModel.Any())
                            {
                                @foreach (Brand item in Model.ViewModel)
                                {
                                    <tr>
                                        <td class="text-truncate">
                                            @item.BrandId
                                        </td>
                                        <td class="text-truncate">
                                            <a class="text-uppercase text-dark" asp-action="Detail" asp-controller="Brand" asp-area="Admin" asp-route-id="@item.BrandId">@item.Name</a>
                                        </td>
                                        <td class="text-truncate">
                                            <img class="img-thumbnail" src="/Images/BrandImage/@item.Image" alt="@item.Name" width="100" />
                                        </td>
                                        <td>
                                            <a class="btn btn-sm btn-outline-danger round mb-0" href="">حذف</a>
                                            <a class="btn btn-sm btn-outline-info round mb-0" asp-action="Edit" asp-area="Admin" asp-controller="Brand" asp-route-id="@item.BrandId">ویرایش</a>
                                            <a class="btn btn-sm btn-outline-primary round mb-0" asp-action="Detail" asp-area="Admin" asp-controller="Brand" asp-route-id="@item.BrandId">نمایش اطلاعات</a>
                                            <a class="btn btn-sm btn-outline-warning round mb-0" asp-controller="Brand" asp-action="Detail" asp-route-id="@item.BrandId">ویو کاربران</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <th colspan="4" class="text-truncate text-danger">در حال حاضر برندی ثبت نشده است</th>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="mt-1">

                        <div class="dataTables_paginate paging_simple_numbers" page-info="@Model.PaginationInfo" action="Index" controller="Brand"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>